---
parent: 'common/test_cases/crio.yml'
overrides:
  timer: 'H H * * *'
  provision:
    os: "rhel"
    stage: "bare"
    provider: "aws"
extensions:
  actions:
    - type: "host_script"
      title: "install CI user account"
      script: |-
        oct prepare user
        sed -i 's/User ec2-user/User origin/g' ./.config/origin-ci-tool/inventory/.ssh_config
    - type: "host_script"
      title: "bootstrap remote host"
      script: |-
        oct bootstrap host
        oct bootstrap node
    - type: "script"
      title: "install git"
      script: |-
        sudo yum install -y git
    - type: "forward_parameters"
      parameters:
        - PULL_NUMBER
        - PULL_BASE_SHA
        - PULL_PULL_SHA
    - type: "script"
      title: "set up cri-o repository"
      script: |-
        sudo mkdir /go
        sudo chmod a+rwx /go
        sudo echo "GOPATH=/go" >> /etc/environment
        mkdir -p /go/src/github.com/kubernetes-incubator
        cd /go/src/github.com/kubernetes-incubator
        git clone https://github.com/kubernetes-incubator/cri-o.git
        cd cri-o
        git branch target "${PULL_BASE_SHA}"
        git checkout target
        git fetch origin "pull/${PULL_NUMBER}/head:pr"
        git merge "${PULL_PULL_SHA}"
    - type: "script"
      title: "set up cri-o dependencies"
      script: |-
        ansible-playbook -vv --become  \
                         -i localhost, \
                         --tags setup  \
                         --become-user root \
                         --connection local \
                         /go/src/github.com/kubernetes-incubator/cri-o/contrib/test/integration/main.yml
    - type: "host_script"
      title: "package the AMI"
      script: |-
        oct package ami --stage=crio
    - type: "script"
      title: "run the cri-o tests"
      script: |-
        ansible-playbook -vv --become  \
                         -i localhost, \
                         --tags integration,critest,e2e \
                         --become-user root \
                         --connection local \
                         /go/src/github.com/kubernetes-incubator/cri-o/contrib/test/integration/main.yml
